//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeMainDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public Nullable<long> status { get; set; }
        public Nullable<long> pwdchangestatus { get; set; }
        public Nullable<long> logoutreason { get; set; }
        public Nullable<long> commitstatus { get; set; }
        public string suggested_skypename { get; set; }
        public string skypeout_balance_currency { get; set; }
        public Nullable<long> skypeout_balance { get; set; }
        public Nullable<long> skypeout_precision { get; set; }
        public string skypein_numbers { get; set; }
        public string subscriptions { get; set; }
        public Nullable<long> cblsyncstatus { get; set; }
        public string offline_callforward { get; set; }
        public Nullable<long> chat_policy { get; set; }
        public Nullable<long> skype_call_policy { get; set; }
        public Nullable<long> pstn_call_policy { get; set; }
        public Nullable<long> avatar_policy { get; set; }
        public Nullable<long> buddycount_policy { get; set; }
        public Nullable<long> timezone_policy { get; set; }
        public Nullable<long> webpresence_policy { get; set; }
        public Nullable<long> phonenumbers_policy { get; set; }
        public Nullable<long> voicemail_policy { get; set; }
        public Nullable<long> authrequest_policy { get; set; }
        public Nullable<long> ad_policy { get; set; }
        public string partner_optedout { get; set; }
        public string service_provider_info { get; set; }
        public Nullable<long> registration_timestamp { get; set; }
        public Nullable<long> nr_of_other_instances { get; set; }
        public string partner_channel_status { get; set; }
        public Nullable<long> flamingo_xmpp_status { get; set; }
        public Nullable<long> federated_presence_policy { get; set; }
        public Nullable<long> owner_under_legal_age { get; set; }
        public Nullable<long> type { get; set; }
        public string skypename { get; set; }
        public string pstnnumber { get; set; }
        public string fullname { get; set; }
        public Nullable<long> birthday { get; set; }
        public Nullable<long> gender { get; set; }
        public string languages { get; set; }
        public string country { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string phone_home { get; set; }
        public string phone_office { get; set; }
        public string phone_mobile { get; set; }
        public string emails { get; set; }
        public string homepage { get; set; }
        public string about { get; set; }
        public Nullable<long> profile_timestamp { get; set; }
        public string received_authrequest { get; set; }
        public string displayname { get; set; }
        public Nullable<long> refreshing { get; set; }
        public Nullable<long> given_authlevel { get; set; }
        public string aliases { get; set; }
        public Nullable<long> authreq_timestamp { get; set; }
        public string mood_text { get; set; }
        public Nullable<long> timezone { get; set; }
        public Nullable<long> nrof_authed_buddies { get; set; }
        public string ipcountry { get; set; }
        public string given_displayname { get; set; }
        public Nullable<long> availability { get; set; }
        public Nullable<long> lastonline_timestamp { get; set; }
        public byte[] capabilities { get; set; }
        public byte[] avatar_image { get; set; }
        public string assigned_speeddial { get; set; }
        public Nullable<long> lastused_timestamp { get; set; }
        public Nullable<long> authrequest_count { get; set; }
        public string assigned_comment { get; set; }
        public string alertstring { get; set; }
        public Nullable<long> avatar_timestamp { get; set; }
        public Nullable<long> mood_timestamp { get; set; }
        public string rich_mood_text { get; set; }
        public byte[] synced_email { get; set; }
        public byte[] options_change_future { get; set; }
        public byte[] cbl_profile_blob { get; set; }
        public Nullable<long> authorized_time { get; set; }
        public string sent_authrequest { get; set; }
        public Nullable<long> sent_authrequest_time { get; set; }
        public Nullable<long> sent_authrequest_serial { get; set; }
        public byte[] buddyblob { get; set; }
        public byte[] cbl_future { get; set; }
        public Nullable<long> node_capabilities { get; set; }
        public Nullable<long> node_capabilities_and { get; set; }
        public Nullable<long> revoked_auth { get; set; }
        public Nullable<long> added_in_shared_group { get; set; }
        public Nullable<long> in_shared_group { get; set; }
        public byte[] authreq_history { get; set; }
        public byte[] profile_attachments { get; set; }
        public Nullable<long> stack_version { get; set; }
        public Nullable<long> offline_authreq_id { get; set; }
        public byte[] verified_email { get; set; }
        public byte[] verified_company { get; set; }
        public string liveid_membername { get; set; }
        public Nullable<long> roaming_history_enabled { get; set; }
        public Nullable<long> uses_jcs { get; set; }
        public Nullable<long> cobrand_id { get; set; }
    }
}
