//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCE.BusinessObjects.SkypeMainDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMembers
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public string chatname { get; set; }
        public string identity { get; set; }
        public Nullable<long> role { get; set; }
        public Nullable<long> is_active { get; set; }
        public Nullable<long> cur_activities { get; set; }
        public string adder { get; set; }
    }
}
