//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeMainDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public Nullable<long> type { get; set; }
        public string skypename { get; set; }
        public string pstnnumber { get; set; }
        public string aliases { get; set; }
        public string fullname { get; set; }
        public Nullable<long> birthday { get; set; }
        public Nullable<long> gender { get; set; }
        public string languages { get; set; }
        public string country { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string phone_home { get; set; }
        public string phone_office { get; set; }
        public string phone_mobile { get; set; }
        public string emails { get; set; }
        public string homepage { get; set; }
        public string about { get; set; }
        public byte[] avatar_image { get; set; }
        public string mood_text { get; set; }
        public string rich_mood_text { get; set; }
        public Nullable<long> timezone { get; set; }
        public byte[] capabilities { get; set; }
        public Nullable<long> profile_timestamp { get; set; }
        public Nullable<long> nrof_authed_buddies { get; set; }
        public string ipcountry { get; set; }
        public Nullable<long> avatar_timestamp { get; set; }
        public Nullable<long> mood_timestamp { get; set; }
        public string received_authrequest { get; set; }
        public Nullable<long> authreq_timestamp { get; set; }
        public Nullable<long> lastonline_timestamp { get; set; }
        public Nullable<long> availability { get; set; }
        public string displayname { get; set; }
        public Nullable<long> refreshing { get; set; }
        public Nullable<long> given_authlevel { get; set; }
        public string given_displayname { get; set; }
        public string assigned_speeddial { get; set; }
        public string assigned_comment { get; set; }
        public string alertstring { get; set; }
        public Nullable<long> lastused_timestamp { get; set; }
        public Nullable<long> authrequest_count { get; set; }
        public string assigned_phone1 { get; set; }
        public string assigned_phone1_label { get; set; }
        public string assigned_phone2 { get; set; }
        public string assigned_phone2_label { get; set; }
        public string assigned_phone3 { get; set; }
        public string assigned_phone3_label { get; set; }
        public Nullable<long> buddystatus { get; set; }
        public Nullable<long> isauthorized { get; set; }
        public Nullable<long> popularity_ord { get; set; }
        public Nullable<long> isblocked { get; set; }
        public byte[] authorization_certificate { get; set; }
        public Nullable<long> certificate_send_count { get; set; }
        public Nullable<long> account_modification_serial_nr { get; set; }
        public byte[] saved_directory_blob { get; set; }
        public Nullable<long> nr_of_buddies { get; set; }
        public Nullable<long> server_synced { get; set; }
        public Nullable<long> contactlist_track { get; set; }
        public Nullable<long> last_used_networktime { get; set; }
        public Nullable<long> authorized_time { get; set; }
        public string sent_authrequest { get; set; }
        public Nullable<long> sent_authrequest_time { get; set; }
        public Nullable<long> sent_authrequest_serial { get; set; }
        public byte[] buddyblob { get; set; }
        public byte[] cbl_future { get; set; }
        public Nullable<long> node_capabilities { get; set; }
        public Nullable<long> revoked_auth { get; set; }
        public Nullable<long> added_in_shared_group { get; set; }
        public Nullable<long> in_shared_group { get; set; }
        public byte[] authreq_history { get; set; }
        public byte[] profile_attachments { get; set; }
        public Nullable<long> stack_version { get; set; }
        public Nullable<long> offline_authreq_id { get; set; }
        public Nullable<long> node_capabilities_and { get; set; }
        public Nullable<long> authreq_crc { get; set; }
        public Nullable<long> authreq_src { get; set; }
        public Nullable<long> pop_score { get; set; }
        public byte[] authreq_nodeinfo { get; set; }
        public string main_phone { get; set; }
        public string unified_servants { get; set; }
        public string phone_home_normalized { get; set; }
        public string phone_office_normalized { get; set; }
        public string phone_mobile_normalized { get; set; }
        public Nullable<long> sent_authrequest_initmethod { get; set; }
        public Nullable<long> authreq_initmethod { get; set; }
        public byte[] verified_email { get; set; }
        public byte[] verified_company { get; set; }
        public Nullable<long> sent_authrequest_extrasbitmask { get; set; }
        public Nullable<long> extprop_seen_birthday { get; set; }
        public Nullable<long> extprop_sms_target { get; set; }
        public string extprop_external_data { get; set; }
        public Nullable<long> extprop_must_hide_avatar { get; set; }
        public string hashed_emails { get; set; }
        public string external_id { get; set; }
        public string external_system_id { get; set; }
        public string liveid_cid { get; set; }
    }
}
