//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeMainDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactGroups
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public Nullable<long> type { get; set; }
        public Nullable<long> custom_group_id { get; set; }
        public string given_displayname { get; set; }
        public Nullable<long> nrofcontacts { get; set; }
        public Nullable<long> nrofcontacts_online { get; set; }
        public Nullable<long> given_sortorder { get; set; }
        public Nullable<long> type_old { get; set; }
        public string proposer { get; set; }
        public string description { get; set; }
        public string associated_chat { get; set; }
        public string members { get; set; }
        public Nullable<long> cbl_id { get; set; }
        public byte[] cbl_blob { get; set; }
        public Nullable<long> @fixed { get; set; }
        public Nullable<long> keep_sharedgroup_contacts { get; set; }
        public string chats { get; set; }
        public Nullable<long> extprop_is_hidden { get; set; }
        public Nullable<long> extprop_sortorder_value { get; set; }
        public Nullable<long> extprop_is_expanded { get; set; }
    }
}
