//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeMainDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSes
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public Nullable<long> type { get; set; }
        public Nullable<long> outgoing_reply_type { get; set; }
        public Nullable<long> status { get; set; }
        public Nullable<long> failurereason { get; set; }
        public Nullable<long> is_failed_unseen { get; set; }
        public Nullable<long> timestamp { get; set; }
        public Nullable<long> price { get; set; }
        public Nullable<long> price_precision { get; set; }
        public string price_currency { get; set; }
        public string reply_to_number { get; set; }
        public string target_numbers { get; set; }
        public byte[] target_statuses { get; set; }
        public string body { get; set; }
        public Nullable<long> chatmsg_id { get; set; }
        public string identity { get; set; }
        public Nullable<long> notification_id { get; set; }
        public Nullable<long> event_flags { get; set; }
        public string reply_id_number { get; set; }
        public string convo_name { get; set; }
        public Nullable<long> extprop_hide_from_history { get; set; }
        public Nullable<long> extprop_extended { get; set; }
    }
}
