//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeMainDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translators
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
    }
}
