//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeMainDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos
    {
        public long id { get; set; }
        public Nullable<long> is_permanent { get; set; }
        public Nullable<long> status { get; set; }
        public string error { get; set; }
        public string debuginfo { get; set; }
        public string dimensions { get; set; }
        public Nullable<long> media_type { get; set; }
        public Nullable<long> duration_1080 { get; set; }
        public Nullable<long> duration_720 { get; set; }
        public Nullable<long> duration_hqv { get; set; }
        public Nullable<long> duration_vgad2 { get; set; }
        public Nullable<long> duration_ltvgad2 { get; set; }
        public Nullable<long> timestamp { get; set; }
        public Nullable<long> hq_present { get; set; }
        public Nullable<long> duration_ss { get; set; }
        public Nullable<long> ss_timestamp { get; set; }
        public Nullable<long> convo_id { get; set; }
        public string device_path { get; set; }
        public string device_name { get; set; }
    }
}
